### PR TITLE
Using frozen requirements from a requirements file

### PR DESCRIPTION
**Pull request by alexjch**
This change moves the list of requirements from a variable in the installation script to a file and includes a version for each requirement that are known to work properly.

### CODE REVIEW

**Comment by phmccarty** [comment]
I hit an install failure with this change, presumably because the repo is cloned to `/tmp` after pip install runs?

```
Could not open requirements file: [Errno 2] No such file or directory: '/tmp/telemetrics-backend/scripts/requirements.txt'
```

**Comment by phmccarty** [comment]
So, I think this solution is okay, but I would like to remove the 'requirements.txt' from the git repo if we are creating it on-the-fly now.

I will test and merge if everything works okay.

**Comment by phmccarty** [comment]
@alexjch I get a different error now:

```
./deploy.sh: line 205: requirements.txt: Permission denied
```

This happens because the current directory is REMOTE_APP_DIR (/var/www/telemetry), and I'm running the script as a non-root user. Perhaps just create the file in TMPDIR?

**Comment by alexjch** [comment]
I squashed the changes and updated the PR with provided reviews.

**Review by phmccarty — APPROVED** [review]
Changes look good, and my testing checks out. Thanks!

**Pull request merged**
